### PR TITLE
Update Makefile

### PR DESCRIPTION
**Pull request by designgears**
Update makefile build output, removed hardcoded drive

### CODE REVIEW

**Comment by XorTroll** [comment]
Welp, I had that for testing...

**Comment by XorTroll** [comment]
Mind adding Reinx support too? I'm personally an atmosphere only user, but want to support all open source CFWs

**Comment by designgears** [comment]
I use atmosphere as well, so didn't think about that. Funny side note just got banned from ReSwitched discord for mentioning ReiNX. (broken rules 8 and 9 by doing it apparently)

**Comment by designgears** [comment]
Closing this

**Pull request closed without merging**
