### PR TITLE
Add translation support

### PR DESCRIPTION
**Pull request by AmonRaNet**
Added support for localization.
I have used Qt like style (base strings in code) - I see as more readable in-comparison to ID based solutions.
To support fast update/create of translation extra make command added: make translation . Currently command updates only Russian language, other can be added in similar way.

TR - default(empty) context
TR_CTX - custom context. Can be used to group strings or to add several translations for same source

P.S. 
 - Russian is translated
 - Spanish is translated (thanks to @impeeza)

### CODE REVIEW

**Comment by impeeza** [comment]
If helps, I am attaching spanish translation
[lng_sp.zip](https://github.com/XorTroll/emuiibo/files/6332113/lng_sp.zip)

Regards

**Comment by AmonRaNet** [comment]
> If helps, I am attaching spanish translation
> [lng_sp.zip](https://github.com/XorTroll/emuiibo/files/6332113/lng_sp.zip)

@impeeza This is really cool! Thanks!
Please can you also add translation for this branch: https://github.com/XorTroll/emuiibo/pull/164

**Comment by impeeza** [comment]
Will try on a bit

**Comment by AmonRaNet** [comment]
@impeeza Actually your file contains translation for both versions :) I have added also to other PR. Thanks

**Comment by impeeza** [comment]
Yes, I just see it, It's better the two files separated or both sections on a file is all right?

**Comment by AmonRaNet** [comment]
> Yes, I just see it, It's better the two files separated or both sections on a file is all right?

Technically it is the same translation system in both PRs, but because a design is fully different - each of them should have dedicated translation file - at least it is more recommended, from other side a combined version would also works for your personal use. Generally we should have decision about final design to have only one version of translations to maintain.

I have split file myself - no worries - other PR also updated and contains subset of yours translation file.

**Comment by amazingfate** [comment]
Is this PR going to get merged? I'm willing to add Chinese Simplified translation.

**Comment by AmonRaNet** [comment]
> Is this PR going to get merged? I'm willing to add Chinese Simplified translation.

I would be happy to merge :) but this is more question to @XorTroll .
In any case if you have already translation you can share it with me - I will add it to PR.

**Comment by AmonRaNet** [comment]
> [lng_cn.zip](https://github.com/XorTroll/emuiibo/files/7308278/lng_cn.zip) @AmonRaNet this is the Chinese translation :)

@amazingfate Thanks!

**Comment by zdm65477730** [comment]
We could use i18n method that EdiZon-Rewrite did:
https://github.com/zdm65477730/EdiZon-Rewrite/blob/master/application/source/ui/gui_main.cpp

**Comment by zdm65477730** [comment]
Here is an example:
"edz.gui.popup.information.playtime"_lang, it will check the translation json file to fetch the correct string.

**Comment by qazrfv1234** [comment]
If possible, the attachment is for Traditional Chinese lang.
many thanks!
[lng_zh-TW.zip](https://github.com/XorTroll/emuiibo/files/7460798/lng_zh-TW.zip)

**Comment by AmonRaNet** [comment]
> Here is an example: "edz.gui.popup.information.playtime"_lang, it will check the translation json file to fetch the correct string.

I like idea with user-define literal - nicer as old school macro :) Also maybe nlohmann json parser can give smaller binary, I will check for sure.
Regarding id-based translations - I am personally more in favor to inline text declaration. Mainly because they are having  better readability and always provide fallback to base lng.

**Comment by AmonRaNet** [comment]
> If possible, the attachment is for Traditional Chinese lang.
> many thanks!
> lng_zh-TW.zip

I have added, but not in this PR. According strings in your file it is for https://github.com/XorTroll/emuiibo/pull/164
You have said "Traditional Chinese", but file named as for "Taiwanese" - it is correct file name?

**Comment by qazrfv1234** [comment]
> I have added, but not in this PR. According strings in your file it is for #164 You have said "Traditional Chinese", but file named as for "Taiwanese" - it is correct file name?
Yes, it's correct. 
The attachment is for Taiwanese.

**Comment by amazingfate** [comment]
> > I have added, but not in this PR. According strings in your file it is for #164 You have said "Traditional Chinese", but file named as for "Taiwanese" - it is correct file name?
> > Yes, it's correct.
> > The attachment is for Taiwanese.

did you test with this filename lng_zh-TW.json?
According to https://switchbrew.org/wiki/Settings_services#LanguageCode, language code for Transitional Chinese should be zh-Hant. Since I have tested zh-Hans works for Simplified Chinese, I think zh-Hant should be the correct language code for you.

**Comment by AmonRaNet** [comment]
> > > I have added, but not in this PR. According strings in your file it is for #164 You have said "Traditional Chinese", but file named as for "Taiwanese" - it is correct file name?
> > > Yes, it's correct.
> > > The attachment is for Taiwanese.
> 
> did you test with this filename lng_zh-TW.json? According to https://switchbrew.org/wiki/Settings_services#LanguageCode, language code for Transitional Chinese should be zh-Hant. Since I have tested zh-Hans works for Simplified Chinese, I think zh-Hant should be the correct language code for you.

Renamed to zh-Hant - this was tested and it works

**Comment by AmonRaNet** [comment]
Deprecated because of https://github.com/XorTroll/emuiibo/pull/164

**Pull request closed without merging**
