### PR TITLE
Reworked overlay

### PR DESCRIPTION
**Pull request by AD2076**
WARNING: needs libtesla from here https://github.com/AD2076/libtesla use it or wait til the PR gets merged in libtesla

ovlemuiibojpg

### CODE REVIEW

**Comment by AD2076** [comment]
no need to use forked libtesla

**Comment by Slluxx** [comment]
looks good +1

**Comment by rusagent** [comment]
How could i make or get a release of this?

**Comment by AD2076** [comment]
Join XorTroll's Discord server

**Comment by AD2076** [comment]
Images ovl worrks again with latest emuiibo

**Comment by AmonRaNet** [comment]
Deprecated because of https://github.com/XorTroll/emuiibo/pull/164

**Comment by XorTroll** [comment]
Closing since the other PR got merged

**Comment by AD2076** [comment]
Finally!

**Pull request closed without merging**
