### PR TITLE
emuiibo rewrite with Rust

### PR DESCRIPTION
**Pull request by XorTroll**
This rewrite is already working, kind of (opening and closing various games/using amiibos in games several times still causes crashes) - this will be merged when everything works properly, and thus emuiibo will completely migrate from C++ and Atmosphere-libs to being made completely in Rust.

Note: the overlay will still make use of C++/libnx/devkitPro.

### CODE REVIEW

**Comment by XorTroll** [comment]
Development of this rewrite is in a fairly good state - emuiibo's functionality is all finished and the rewrite seems to work as 0.5.x emuiibo did.
All what's left is some intense testing to locate and fix any possible bugs ;)

**Review by impeeza — COMMENTED** [review]
Thanks a lot for your great work and effort

**Comment by XorTroll** [comment]
With this rewrite:
- output NSP size dropped from ~500KB (last emuiibo release) to ~100KB
- same heap memory size works fine, smaller heap might also work (meaning this rewrite might use even less memory)

**Comment by XorTroll** [comment]
After having let users test this rewrite on Discord, the results are quite impressive:

- emuiibo's heap memory usage has dropped from 0x40000 to 0x4000 (this is quite surprising, considering last version had to increase heap memory size from 0x20000 to 0x40000 to avoid random crashes, while with Rust a size of 0x4000 never gave any kind of issues to anyone testing it!)

- emuiibo's binary size (size of the NSO binary, and hence the exefs NSP) dropped from ~500KB to ~160KB, which is not that relevant for the end user, but still a surprising change

- In terms of speed (how fast emuiibo's simulated amiibo services work) this rewrite used to have some speed problems which could be noticed by the end user, but after optimizations on IPC server code it is now as fast as the C++ version, if not even faster ;)

Therefore, after all the work invested into this rewrite, it is finally ready to deprecate the C++ code and to release 0.6 as soon as possible ;)

**Comment by A6GibKm** [comment]
:crab:

**Comment by impeeza** [comment]
Guaw, this is impressive,  Kudos on all the hard work.

**Pull request merged**
