### PR TITLE
Redesigned emuGUIibo

### PR DESCRIPTION
**Pull request by Samyocord**
I redesigned emuGUIibo. It uses Material Design instead of the standard WinForms Design.

### CODE REVIEW

**Comment by Enspiron** [comment]
mind sharing some screenshots? I'd like to see the difference.

**Comment by Samyocord** [comment]
https://i.imgur.com/bR0tsOY.png
https://i.imgur.com/TZrDAAN.png
https://i.imgur.com/4puM9Sq.png

**Comment by lookye** [comment]
You have some debug code left in the PR.

**Comment by Samyocord** [comment]
Removed the debug files. Sorry for the many commits, I am on my phone right now.

**Comment by mrbob312** [comment]
Would it be ok if I merge this into my fork? (My fork has some bugfixes)

**Comment by Samyocord** [comment]
yes

**Pull request closed without merging**
